/**
 * AUTO-GENERATED by scripts/wikidata/generate-leaders.mjs
 *
 * Last refreshed: 2025-01 (bootstrap from existing data)
 * Source: Wikidata Action API (https://www.wikidata.org/w/api.php)
 *
 * DO NOT EDIT MANUALLY. To refresh, run: pnpm run generate:leaders
 *
 * This file is committed to the repo as a fallback in case Wikidata
 * is unreachable during a build. The build pipeline refreshes it
 * automatically before each Vite build.
 */

import type { Question } from "./types";

export const africaPresidents: Question[] = [
  {
    q: "President of Nigeria (2025)?",
    a: "Bola Tinubu",
    opts: ["Peter Obi", "Atiku Abubakar", "Bola Tinubu", "Yemi Osinbajo"],
    lvl: 1,
  },
  {
    q: "President of South Africa?",
    a: "Cyril Ramaphosa",
    opts: ["Jacob Zuma", "Cyril Ramaphosa", "Julius Malema", "Thabo Mbeki"],
    lvl: 1,
  },
  {
    q: "President of Kenya?",
    a: "William Ruto",
    opts: ["Raila Odinga", "Uhuru Kenyatta", "William Ruto", "Daniel Moi"],
    lvl: 1,
  },
  {
    q: "President of Rwanda?",
    a: "Paul Kagame",
    opts: [
      "Pasteur Bizimungu",
      "Paul Kagame",
      "Juvenal Habyarimana",
      "Kayibanda",
    ],
    lvl: 1,
  },
  {
    q: "President of Ghana (2025)?",
    a: "John Mahama",
    opts: ["John Mahama", "Nana Akufo-Addo", "Jerry Rawlings", "John Kufuor"],
    lvl: 1,
  },
  {
    q: "President of Egypt?",
    a: "Abdel Fattah el-Sisi",
    opts: [
      "Hosni Mubarak",
      "Mohamed Morsi",
      "Abdel Fattah el-Sisi",
      "Anwar Sadat",
    ],
    lvl: 1,
  },
  {
    q: "President of Uganda?",
    a: "Yoweri Museveni",
    opts: ["Bobi Wine", "Yoweri Museveni", "Idi Amin", "Milton Obote"],
    lvl: 1,
  },
  {
    q: "President of Senegal (2025)?",
    a: "Bassirou Diomaye Faye",
    opts: [
      "Macky Sall",
      "Bassirou Diomaye Faye",
      "Ousmane Sonko",
      "Abdoulaye Wade",
    ],
    lvl: 1,
  },
  {
    q: "President of Zimbabwe?",
    a: "Emmerson Mnangagwa",
    opts: [
      "Robert Mugabe",
      "Morgan Tsvangirai",
      "Emmerson Mnangagwa",
      "Nelson Chamisa",
    ],
    lvl: 2,
  },
  {
    q: "President of Tanzania?",
    a: "Samia Suluhu Hassan",
    opts: [
      "John Magufuli",
      "Samia Suluhu Hassan",
      "Jakaya Kikwete",
      "Benjamin Mkapa",
    ],
    lvl: 2,
  },
  {
    q: "President of Algeria?",
    a: "Abdelmadjid Tebboune",
    opts: [
      "Abdelmadjid Tebboune",
      "Abdelaziz Bouteflika",
      "Ahmed Bensalah",
      "Liamine Zeroual",
    ],
    lvl: 2,
  },
  {
    q: "President of Ethiopia?",
    a: "Taye Atske Selassie",
    opts: [
      "Sahle-Work Zewde",
      "Taye Atske Selassie",
      "Mulatu Teshome",
      "Girma Wolde-Giorgis",
    ],
    lvl: 2,
  },
  {
    q: "President of Angola?",
    a: "Joao Lourenco",
    opts: [
      "Jose Eduardo dos Santos",
      "Joao Lourenco",
      "Antonio Agostinho Neto",
      "Manuel Vicente",
    ],
    lvl: 2,
  },
  {
    q: "President of Mozambique?",
    a: "Daniel Chapo",
    opts: [
      "Filipe Nyusi",
      "Daniel Chapo",
      "Armando Guebuza",
      "Joaquim Chissano",
    ],
    lvl: 2,
  },
  {
    q: "President of Ivory Coast?",
    a: "Alassane Ouattara",
    opts: [
      "Alassane Ouattara",
      "Laurent Gbagbo",
      "Henri Konan Bedie",
      "Robert Guei",
    ],
    lvl: 2,
  },
  {
    q: "President of Cameroon?",
    a: "Paul Biya",
    opts: ["Paul Biya", "Ahmadou Ahidjo", "Maurice Kamto", "John Fru Ndi"],
    lvl: 2,
  },
  {
    q: "President of Namibia?",
    a: "Netumbo Nandi-Ndaitwah",
    opts: [
      "Hage Geingob",
      "Netumbo Nandi-Ndaitwah",
      "Sam Nujoma",
      "Hifikepunye Pohamba",
    ],
    lvl: 3,
  },
  {
    q: "President of Botswana?",
    a: "Duma Boko",
    opts: ["Mokgweetsi Masisi", "Duma Boko", "Ian Khama", "Festus Mogae"],
    lvl: 3,
  },
  {
    q: "President of Madagascar?",
    a: "Andry Rajoelina",
    opts: [
      "Andry Rajoelina",
      "Marc Ravalomanana",
      "Hery Rajaonarimampianina",
      "Didier Ratsiraka",
    ],
    lvl: 3,
  },
  {
    q: "President of Zambia?",
    a: "Hakainde Hichilema",
    opts: ["Edgar Lungu", "Hakainde Hichilema", "Michael Sata", "Rupiah Banda"],
    lvl: 3,
  },
  {
    q: "President of Burkina Faso?",
    a: "Ibrahim Traore",
    opts: [
      "Ibrahim Traore",
      "Roch Marc Christian Kabore",
      "Paul-Henri Damiba",
      "Blaise Compaore",
    ],
    lvl: 3,
  },
  {
    q: "President of Mali?",
    a: "Assimi Goita",
    opts: [
      "Assimi Goita",
      "Ibrahim Boubacar Keita",
      "Bah N'Daw",
      "Amadou Toumani Toure",
    ],
    lvl: 3,
  },
  {
    q: "President of Chad?",
    a: "Mahamat Idriss Deby",
    opts: [
      "Mahamat Idriss Deby",
      "Idriss Deby",
      "Hissene Habre",
      "Francois Tombalbaye",
    ],
    lvl: 3,
  },
  {
    q: "President of DRC?",
    a: "Felix Tshisekedi",
    opts: [
      "Felix Tshisekedi",
      "Joseph Kabila",
      "Laurent-Desire Kabila",
      "Mobutu Sese Seko",
    ],
    lvl: 3,
  },
];

export const asiaPresidents: Question[] = [
  {
    q: "Prime Minister of Japan (2025)?",
    a: "Shigeru Ishiba",
    opts: ["Fumio Kishida", "Shigeru Ishiba", "Yoshihide Suga", "Shinzo Abe"],
    lvl: 1,
  },
  {
    q: "President of China?",
    a: "Xi Jinping",
    opts: ["Li Qiang", "Xi Jinping", "Hu Jintao", "Wang Yi"],
    lvl: 1,
  },
  {
    q: "Prime Minister of India (2025)?",
    a: "Narendra Modi",
    opts: ["Rahul Gandhi", "Narendra Modi", "Manmohan Singh", "Amit Shah"],
    lvl: 1,
  },
  {
    q: "President of South Korea?",
    a: "Yoon Suk-yeol",
    opts: ["Moon Jae-in", "Yoon Suk-yeol", "Park Geun-hye", "Lee Jae-myung"],
    lvl: 1,
  },
  {
    q: "President of Indonesia (2025)?",
    a: "Prabowo Subianto",
    opts: [
      "Joko Widodo",
      "Prabowo Subianto",
      "Anies Baswedan",
      "Megawati Sukarnoputri",
    ],
    lvl: 1,
  },
  {
    q: "King of Saudi Arabia?",
    a: "Salman bin Abdulaziz",
    opts: [
      "Mohammed bin Salman",
      "Salman bin Abdulaziz",
      "Abdullah bin Abdulaziz",
      "Fahd bin Abdulaziz",
    ],
    lvl: 1,
  },
  {
    q: "President of Turkey?",
    a: "Recep Tayyip Erdogan",
    opts: [
      "Recep Tayyip Erdogan",
      "Kemal Kilicdaroglu",
      "Abdullah Gul",
      "Ahmet Davutoglu",
    ],
    lvl: 1,
  },
  {
    q: "President of Philippines (2025)?",
    a: "Ferdinand Marcos Jr.",
    opts: [
      "Rodrigo Duterte",
      "Ferdinand Marcos Jr.",
      "Leni Robredo",
      "Bongbong Marcos",
    ],
    lvl: 1,
  },
  {
    q: "Prime Minister of Pakistan (2025)?",
    a: "Shehbaz Sharif",
    opts: ["Imran Khan", "Shehbaz Sharif", "Nawaz Sharif", "Bilawal Bhutto"],
    lvl: 2,
  },
  {
    q: "Supreme Leader of Iran?",
    a: "Ali Khamenei",
    opts: [
      "Ali Khamenei",
      "Masoud Pezeshkian",
      "Ebrahim Raisi",
      "Hassan Rouhani",
    ],
    lvl: 2,
  },
  {
    q: "Prime Minister of Vietnam?",
    a: "Pham Minh Chinh",
    opts: ["Pham Minh Chinh", "Nguyen Xuan Phuc", "Nguyen Phu Trong", "To Lam"],
    lvl: 2,
  },
  {
    q: "Prime Minister of Malaysia (2025)?",
    a: "Anwar Ibrahim",
    opts: [
      "Anwar Ibrahim",
      "Muhyiddin Yassin",
      "Mahathir Mohamad",
      "Ismail Sabri",
    ],
    lvl: 2,
  },
  {
    q: "Prime Minister of Thailand (2025)?",
    a: "Paetongtarn Shinawatra",
    opts: [
      "Srettha Thavisin",
      "Paetongtarn Shinawatra",
      "Prayut Chan-o-cha",
      "Thaksin Shinawatra",
    ],
    lvl: 2,
  },
  {
    q: "President of Bangladesh (2025)?",
    a: "Mohammed Shahabuddin",
    opts: [
      "Mohammed Shahabuddin",
      "Sheikh Hasina",
      "Muhammad Yunus",
      "Zillur Rahman",
    ],
    lvl: 2,
  },
  {
    q: "Prime Minister of Israel (2025)?",
    a: "Benjamin Netanyahu",
    opts: [
      "Benjamin Netanyahu",
      "Yair Lapid",
      "Naftali Bennett",
      "Benny Gantz",
    ],
    lvl: 2,
  },
  {
    q: "President of Iraq?",
    a: "Abdul Latif Rashid",
    opts: [
      "Abdul Latif Rashid",
      "Barham Salih",
      "Fuad Masum",
      "Nouri al-Maliki",
    ],
    lvl: 2,
  },
  {
    q: "President of Kazakhstan?",
    a: "Kassym-Jomart Tokayev",
    opts: [
      "Nursultan Nazarbayev",
      "Kassym-Jomart Tokayev",
      "Karim Massimov",
      "Dariga Nazarbayeva",
    ],
    lvl: 3,
  },
  {
    q: "President of Uzbekistan?",
    a: "Shavkat Mirziyoyev",
    opts: [
      "Shavkat Mirziyoyev",
      "Islam Karimov",
      "Abdulaziz Kamilov",
      "Rustam Azimov",
    ],
    lvl: 3,
  },
  {
    q: "Prime Minister of Cambodia?",
    a: "Hun Manet",
    opts: ["Hun Sen", "Hun Manet", "Sam Rainsy", "Kem Sokha"],
    lvl: 3,
  },
  {
    q: "President of Mongolia?",
    a: "Ukhnaagiin Khurelsukh",
    opts: [
      "Ukhnaagiin Khurelsukh",
      "Battulga Khaltmaa",
      "Elbegdorj Tsakhia",
      "Enkhbayar Nambar",
    ],
    lvl: 3,
  },
  {
    q: "President of Sri Lanka (2025)?",
    a: "Anura Kumara Dissanayake",
    opts: [
      "Ranil Wickremesinghe",
      "Anura Kumara Dissanayake",
      "Gotabaya Rajapaksa",
      "Sajith Premadasa",
    ],
    lvl: 3,
  },
  {
    q: "Prime Minister of Nepal (2025)?",
    a: "KP Sharma Oli",
    opts: [
      "Sher Bahadur Deuba",
      "KP Sharma Oli",
      "Pushpa Kamal Dahal",
      "Baburam Bhattarai",
    ],
    lvl: 3,
  },
  {
    q: "President of Laos?",
    a: "Thongloun Sisoulith",
    opts: [
      "Thongloun Sisoulith",
      "Bounnhang Vorachith",
      "Choummaly Sayasone",
      "Khamtai Siphandon",
    ],
    lvl: 3,
  },
  {
    q: "President of UAE?",
    a: "Mohamed bin Zayed Al Nahyan",
    opts: [
      "Mohamed bin Zayed Al Nahyan",
      "Mohammed bin Rashid",
      "Khalifa bin Zayed",
      "Tamim bin Hamad",
    ],
    lvl: 3,
  },
];

export const europePresidents: Question[] = [
  {
    q: "President of France (2025)?",
    a: "Emmanuel Macron",
    opts: [
      "Emmanuel Macron",
      "Marine Le Pen",
      "Nicolas Sarkozy",
      "Francois Hollande",
    ],
    lvl: 1,
  },
  {
    q: "Chancellor of Germany (2025)?",
    a: "Friedrich Merz",
    opts: ["Olaf Scholz", "Friedrich Merz", "Angela Merkel", "Robert Habeck"],
    lvl: 1,
  },
  {
    q: "Prime Minister of UK (2025)?",
    a: "Keir Starmer",
    opts: ["Rishi Sunak", "Keir Starmer", "Boris Johnson", "Liz Truss"],
    lvl: 1,
  },
  {
    q: "Prime Minister of Italy (2025)?",
    a: "Giorgia Meloni",
    opts: [
      "Mario Draghi",
      "Giorgia Meloni",
      "Giuseppe Conte",
      "Silvio Berlusconi",
    ],
    lvl: 1,
  },
  {
    q: "President of Russia?",
    a: "Vladimir Putin",
    opts: [
      "Dmitry Medvedev",
      "Vladimir Putin",
      "Mikhail Mishustin",
      "Sergey Lavrov",
    ],
    lvl: 1,
  },
  {
    q: "Prime Minister of Spain (2025)?",
    a: "Pedro Sanchez",
    opts: [
      "Pedro Sanchez",
      "Mariano Rajoy",
      "Alberto Nunez Feijoo",
      "Pablo Iglesias",
    ],
    lvl: 1,
  },
  {
    q: "Prime Minister of Netherlands (2025)?",
    a: "Dick Schoof",
    opts: ["Mark Rutte", "Dick Schoof", "Geert Wilders", "Frans Timmermans"],
    lvl: 1,
  },
  {
    q: "President of Poland?",
    a: "Andrzej Duda",
    opts: ["Andrzej Duda", "Donald Tusk", "Mateusz Morawiecki", "Lech Walesa"],
    lvl: 1,
  },
  {
    q: "Prime Minister of Sweden (2025)?",
    a: "Ulf Kristersson",
    opts: [
      "Stefan Lofven",
      "Ulf Kristersson",
      "Magdalena Andersson",
      "Carl Bildt",
    ],
    lvl: 2,
  },
  {
    q: "Prime Minister of Norway (2025)?",
    a: "Jonas Gahr Store",
    opts: [
      "Jonas Gahr Store",
      "Erna Solberg",
      "Jens Stoltenberg",
      "Siv Jensen",
    ],
    lvl: 2,
  },
  {
    q: "Prime Minister of Denmark (2025)?",
    a: "Mette Frederiksen",
    opts: [
      "Mette Frederiksen",
      "Lars Lokke Rasmussen",
      "Helle Thorning-Schmidt",
      "Anders Fogh",
    ],
    lvl: 2,
  },
  {
    q: "President of Finland?",
    a: "Alexander Stubb",
    opts: ["Sauli Niinisto", "Alexander Stubb", "Tarja Halonen", "Sanna Marin"],
    lvl: 2,
  },
  {
    q: "Prime Minister of Greece (2025)?",
    a: "Kyriakos Mitsotakis",
    opts: [
      "Alexis Tsipras",
      "Kyriakos Mitsotakis",
      "George Papandreou",
      "Antonis Samaras",
    ],
    lvl: 2,
  },
  {
    q: "President of Ukraine?",
    a: "Volodymyr Zelenskyy",
    opts: [
      "Petro Poroshenko",
      "Volodymyr Zelenskyy",
      "Viktor Yanukovych",
      "Leonid Kuchma",
    ],
    lvl: 2,
  },
  {
    q: "Prime Minister of Portugal (2025)?",
    a: "Luis Montenegro",
    opts: [
      "Antonio Costa",
      "Luis Montenegro",
      "Marcelo Rebelo de Sousa",
      "Pedro Passos Coelho",
    ],
    lvl: 2,
  },
  {
    q: "Chancellor of Austria (2025)?",
    a: "Alexander Schallenberg",
    opts: [
      "Karl Nehammer",
      "Alexander Schallenberg",
      "Sebastian Kurz",
      "Herbert Kickl",
    ],
    lvl: 2,
  },
  {
    q: "President of Romania?",
    a: "Nicusor Dan",
    opts: [
      "Klaus Iohannis",
      "Nicusor Dan",
      "Traian Basescu",
      "Calin Georgescu",
    ],
    lvl: 3,
  },
  {
    q: "Prime Minister of Hungary (2025)?",
    a: "Viktor Orban",
    opts: ["Viktor Orban", "Peter Magyar", "Janos Ader", "Gordon Bajnai"],
    lvl: 3,
  },
  {
    q: "Prime Minister of Croatia (2025)?",
    a: "Andrej Plenkovic",
    opts: [
      "Andrej Plenkovic",
      "Zoran Milanovic",
      "Kolinda Grabar-Kitarovic",
      "Tihomir Oreskovic",
    ],
    lvl: 3,
  },
  {
    q: "President of Serbia?",
    a: "Aleksandar Vucic",
    opts: [
      "Aleksandar Vucic",
      "Ana Brnabic",
      "Tomislav Nikolic",
      "Boris Tadic",
    ],
    lvl: 3,
  },
  {
    q: "President of Czech Republic?",
    a: "Petr Pavel",
    opts: ["Milos Zeman", "Petr Pavel", "Vaclav Klaus", "Andrej Babis"],
    lvl: 3,
  },
  {
    q: "President of Bulgaria?",
    a: "Rumen Radev",
    opts: [
      "Rumen Radev",
      "Boyko Borisov",
      "Rosen Plevneliev",
      "Georgi Parvanov",
    ],
    lvl: 3,
  },
  {
    q: "President of Iceland?",
    a: "Halla Tomasdottir",
    opts: [
      "Gudni Johannesson",
      "Halla Tomasdottir",
      "Vigdis Finnbogadottir",
      "Olafur Ragnar Grimsson",
    ],
    lvl: 3,
  },
  {
    q: "President of Slovakia?",
    a: "Peter Pellegrini",
    opts: [
      "Zuzana Caputova",
      "Peter Pellegrini",
      "Robert Fico",
      "Andrej Kiska",
    ],
    lvl: 3,
  },
];

export const americasPresidents: Question[] = [
  {
    q: "President of the United States (2025)?",
    a: "Donald Trump",
    opts: ["Joe Biden", "Donald Trump", "Kamala Harris", "Barack Obama"],
    lvl: 1,
  },
  {
    q: "Prime Minister of Canada (2025)?",
    a: "Mark Carney",
    opts: [
      "Justin Trudeau",
      "Mark Carney",
      "Pierre Poilievre",
      "Jagmeet Singh",
    ],
    lvl: 1,
  },
  {
    q: "President of Brazil (2025)?",
    a: "Lula da Silva",
    opts: ["Jair Bolsonaro", "Lula da Silva", "Dilma Rousseff", "Michel Temer"],
    lvl: 1,
  },
  {
    q: "President of Mexico (2025)?",
    a: "Claudia Sheinbaum",
    opts: [
      "Andres Manuel Lopez Obrador",
      "Claudia Sheinbaum",
      "Enrique Pena Nieto",
      "Xochitl Galvez",
    ],
    lvl: 1,
  },
  {
    q: "President of Argentina (2025)?",
    a: "Javier Milei",
    opts: [
      "Alberto Fernandez",
      "Javier Milei",
      "Cristina Kirchner",
      "Mauricio Macri",
    ],
    lvl: 1,
  },
  {
    q: "President of Colombia?",
    a: "Gustavo Petro",
    opts: ["Ivan Duque", "Gustavo Petro", "Alvaro Uribe", "Juan Manuel Santos"],
    lvl: 1,
  },
  {
    q: "President of Peru?",
    a: "Dina Boluarte",
    opts: [
      "Pedro Castillo",
      "Dina Boluarte",
      "Martin Vizcarra",
      "Keiko Fujimori",
    ],
    lvl: 1,
  },
  {
    q: "President of Cuba?",
    a: "Miguel Diaz-Canel",
    opts: ["Raul Castro", "Miguel Diaz-Canel", "Fidel Castro", "Esteban Lazo"],
    lvl: 1,
  },
  {
    q: "President of Chile (2025)?",
    a: "Gabriel Boric",
    opts: [
      "Sebastian Pinera",
      "Gabriel Boric",
      "Michelle Bachelet",
      "Eduardo Frei",
    ],
    lvl: 2,
  },
  {
    q: "President of Venezuela?",
    a: "Nicolas Maduro",
    opts: ["Nicolas Maduro", "Juan Guaido", "Edmundo Gonzalez", "Hugo Chavez"],
    lvl: 2,
  },
  {
    q: "President of Ecuador?",
    a: "Daniel Noboa",
    opts: ["Guillermo Lasso", "Daniel Noboa", "Rafael Correa", "Lenin Moreno"],
    lvl: 2,
  },
  {
    q: "President of Uruguay?",
    a: "Yamandu Orsi",
    opts: ["Luis Lacalle Pou", "Yamandu Orsi", "Tabare Vazquez", "Jose Mujica"],
    lvl: 2,
  },
  {
    q: "President of Bolivia?",
    a: "Luis Arce",
    opts: ["Evo Morales", "Luis Arce", "Jeanine Anez", "Carlos Mesa"],
    lvl: 2,
  },
  {
    q: "President of Panama (2025)?",
    a: "Jose Raul Mulino",
    opts: [
      "Laurentino Cortizo",
      "Jose Raul Mulino",
      "Juan Carlos Varela",
      "Ricardo Martinelli",
    ],
    lvl: 2,
  },
  {
    q: "Prime Minister of Jamaica (2025)?",
    a: "Andrew Holness",
    opts: [
      "Andrew Holness",
      "Portia Simpson-Miller",
      "P.J. Patterson",
      "Bruce Golding",
    ],
    lvl: 2,
  },
  {
    q: "President of Costa Rica?",
    a: "Rodrigo Chaves",
    opts: [
      "Rodrigo Chaves",
      "Carlos Alvarado",
      "Luis Guillermo Solis",
      "Laura Chinchilla",
    ],
    lvl: 2,
  },
  {
    q: "President of Paraguay?",
    a: "Santiago Pena",
    opts: [
      "Mario Abdo Benitez",
      "Santiago Pena",
      "Horacio Cartes",
      "Fernando Lugo",
    ],
    lvl: 3,
  },
  {
    q: "President of Guatemala?",
    a: "Bernardo Arevalo",
    opts: [
      "Alejandro Giammattei",
      "Bernardo Arevalo",
      "Jimmy Morales",
      "Otto Perez Molina",
    ],
    lvl: 3,
  },
  {
    q: "President of Honduras?",
    a: "Xiomara Castro",
    opts: [
      "Juan Orlando Hernandez",
      "Xiomara Castro",
      "Porfirio Lobo",
      "Manuel Zelaya",
    ],
    lvl: 3,
  },
  {
    q: "President of El Salvador (2025)?",
    a: "Nayib Bukele",
    opts: [
      "Nayib Bukele",
      "Salvador Sanchez Ceren",
      "Mauricio Funes",
      "Alfredo Cristiani",
    ],
    lvl: 3,
  },
  {
    q: "President of Nicaragua?",
    a: "Daniel Ortega",
    opts: [
      "Daniel Ortega",
      "Enrique Bolanos",
      "Violeta Chamorro",
      "Arnoldo Aleman",
    ],
    lvl: 3,
  },
  {
    q: "President of Dominican Republic?",
    a: "Luis Abinader",
    opts: [
      "Luis Abinader",
      "Danilo Medina",
      "Leonel Fernandez",
      "Hipolito Mejia",
    ],
    lvl: 3,
  },
  {
    q: "President of Guyana?",
    a: "Irfaan Ali",
    opts: ["Irfaan Ali", "David Granger", "Donald Ramotar", "Bharrat Jagdeo"],
    lvl: 3,
  },
  {
    q: "Prime Minister of Trinidad and Tobago?",
    a: "Keith Rowley",
    opts: [
      "Keith Rowley",
      "Kamla Persad-Bissessar",
      "Patrick Manning",
      "Basdeo Panday",
    ],
    lvl: 3,
  },
];
